### ISSUE TITLE
Beneos Search - Module: "Import new Content" is still hard to press

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#90] opened 2023-10-08 14:18 UTC
https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/3ac0708e-e535-4c1f-9ed1-c147b0a71f9e

As you can see in this video you need to hit the exact angle to hit the button.

**Comment by LeRatierBretonnien** [comment] 2023-10-08 21:59
Unable to reproduce, but should be fixed

**Closed by LeRatierBretonnien** 2023-10-08 21:59 UTC
